GET http://127.0.0.1:8000/api/v1/movies/

###

GET http://127.0.0.1:8000/api/v1/movies/1/

###

POST http://127.0.0.1:8000/api/v1/movies/
Content-Type: application/json

{
    "title": "Terminator 4",
    "description": "",
    "release_date": "1999-03-23",
    "genres": [
        1
    ]
}

###

PUT http://127.0.0.1:8000/api/v1/movies/4/
Content-Type: application/json

{
    "title": "Terminator 4",
    "description": "Test 77777",
    "release_date": "1999-03-23",
    "genres": [
        1
    ]
}


###
DELETE http://127.0.0.1:8000/api/v1/movies/4/


### Filtering
GET http://127.0.0.1:8000/api/v1/movies/?genres=2


### Searching
GET http://127.0.0.1:8000/api/v1/movies/?search=fgd


### Filtering & Searching
GET http://127.0.0.1:8000/api/v1/movies/?genres=1&search=term


### Ordering ASC / DESC with -
GET http://127.0.0.1:8000/api/v1/movies/?ordering=duration


### Pagination
GET http://127.0.0.1:8000/api/v1/movies/?page=1
