version: "3.8"

services:
    app:
        build: .
        env_file: 
            - .env
        environment: 
            - DEBUG=True
        depends_on: 
            - db
        volumes: 
            - .:/app/
        ports:
            - 8000:8000
        command: python /app/manage.py runserver 0.0.0.0:8000

    db:
        image: mariadb:10.5
        environment: 
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DJANGO_DB_NAME}
            - MARIADB_USER=${DJANGO_DB_USER}
            - MARIADB_PASSWORD=${DJANGO_DB_PASSWORD}
        volumes: 
            - ./data/db:/var/lib/mysql